### ISSUE TITLE
Retornar ID da criação

### ISSUE THREAD

**Issue by polillomm** [tech-espm/labs-master-reading#8]
Consertar o retorno de ID quando é criado um registro na tabela de usuário e de publicação, visando a reutilização do mesmo. Atualmente há esse retorno, contudo ele não está respeitando o assincronismo e, portanto, não está aguardando o valor para retorná-lo.

**Comment by matheuspolillo** [comment]
Ignorado

**Comment by polillomm** [comment]
Ignorado
